  
version: '3.2'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run dev"
volumes:
  dbdata:
